package com.project.entity;

import java.sql.Timestamp;
import jakarta.persistence.*;

/**
 * This is a class that models an TvPost.
 *
 * You should NOT make any modifications to this class.
 */
@Entity
public class TvPost {
    /**
     * An id for this TvPost. You should use this as the Entity's ID.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Integer id;
    /**
     * A userID for this TvPost (must be unique and not blank)
     */
    private Integer userId;
    /**
     * A rawMessage for this TvPost (must be over 4 characters)
     */
    private String rawMessage;
    /**
     * A default, no-args constructor, as well as correctly formatted getters and setters, are needed for
     * Jackson Objectmapper to work.
     */
    private Timestamp date;
    public TvPost(){

    }
    /**
     * When posting a new TvPost, the id can be generated by the database. In that case, a constructor without
     * id is needed.
     * @param userId
     * @param rawMessage
     * @param date
     */
    public TvPost(Integer userId, String rawMessage, Timestamp date){
        this.userId = userId;
        this.rawMessage = rawMessage;
        this.date = date;
    }
    /**
     * Whem retrieving an TvPost from the database, all fields will be needed. In that case, a constructor with all
     * fields is needed.
     * @param id
     * @param userId
     * @param userID
     * @param rawMessage
     */
    public TvPost(Integer id, Integer userId, String rawMessage, Timestamp date) {
        this.id = id;
        this.userId = userId;
        this.rawMessage = rawMessage;
        this.date = date;
    }
    /**
     * Properly named getters and setters are necessary for Jackson ObjectMapper to work. You may use them as well.
     * @return id
     */
    public Integer getId() {
        return id;
    }
    /**
     * Properly named getters and setters are necessary for Jackson ObjectMapper to work. You may use them as well.
     * @param id
     */
    public void setId(Integer id) {
        this.id = id;
    }
    /**
     * Properly named getters and setters are necessary for Jackson ObjectMapper to work. You may use them as well.
     * @return userId
     */
    public Integer getUserId() {
        return userId;
    }
    /**
     * Properly named getters and setters are necessary for Jackson ObjectMapper to work. You may use them as well.
     * @param userId
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    /**
     * Properly named getters and setters are necessary for Jackson ObjectMapper to work. You may use them as well.
     * @return rawMessage
     */
    public String getRawMessage() {
        return rawMessage;
    }
    /**
     * Properly named getters and setters are necessary for Jackson ObjectMapper to work. You may use them as well.
     * @param rawMessage
     */
    public void setRawMessage(String rawMessage) {
        this.rawMessage = rawMessage;
    }

    public Timestamp getDate() {
        return date;
    }
    /**
     * Properly named getters and setters are necessary for Jackson ObjectMapper to work. You may use them as well.
     * @param date
     */
    public void setDate(Timestamp date) {
        this.date = date;
    }
    /**
     * Overriding the default equals() method adds functionality to tell when two objects are identical, allowing
     * Assert.assertEquals and List.contains to function.
     * @param o the other object.
     * @return true if o is equal to this object.
     */
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		TvPost other = (TvPost) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		if (rawMessage == null) {
			if (other.rawMessage != null)
				return false;
		} else if (!rawMessage.equals(other.rawMessage))
			return false;
		if (userId == null) {
			if (other.userId != null)
				return false;
		} else if (!userId.equals(other.userId))
			return false;
        if (date == null) {
            if (other.date != null)
                return false;
        } else if (!date.equals(other.date))
            return false;
		return true;
	}

    /**
     * Overriding the default toString() method allows for easy debugging.
     * @return a String representation of this class.
     */
    @Override
    public String toString() {
        return "TvPost{" +
                "id=" + id +
                ", userId=" + userId +
                ", rawMessage='" + rawMessage + '\'' +
                ", date=" + date +
                '}';
    }
}